// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANzNmokpqQzm7HjSRKuW_t8BXaLgBuB3k',
    appId: '1:228043066675:web:aa79490f4f1ab004140246',
    messagingSenderId: '228043066675',
    projectId: 'interntask-41be2',
    authDomain: 'interntask-41be2.firebaseapp.com',
    storageBucket: 'interntask-41be2.firebasestorage.app',
    measurementId: 'G-C3YPZRDTMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuk8mp1IVY8iuGAZcgv8XjSAn_SIxWcPM',
    appId: '1:228043066675:android:2e12a2c7ceb8a12e140246',
    messagingSenderId: '228043066675',
    projectId: 'interntask-41be2',
    storageBucket: 'interntask-41be2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyqDudnfEYUM-Tbh2_FZx3-4Z7JTBOEmc',
    appId: '1:228043066675:ios:cbe84ff89614eb44140246',
    messagingSenderId: '228043066675',
    projectId: 'interntask-41be2',
    storageBucket: 'interntask-41be2.firebasestorage.app',
    androidClientId: '228043066675-2n0v3ualur3mdl7utj8297qhvmfcvsrg.apps.googleusercontent.com',
    iosClientId: '228043066675-qdvbsvr8t1dlsh5gl6j86tbj1velq11g.apps.googleusercontent.com',
    iosBundleId: 'com.example.interntask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyqDudnfEYUM-Tbh2_FZx3-4Z7JTBOEmc',
    appId: '1:228043066675:ios:cbe84ff89614eb44140246',
    messagingSenderId: '228043066675',
    projectId: 'interntask-41be2',
    storageBucket: 'interntask-41be2.firebasestorage.app',
    androidClientId: '228043066675-2n0v3ualur3mdl7utj8297qhvmfcvsrg.apps.googleusercontent.com',
    iosClientId: '228043066675-qdvbsvr8t1dlsh5gl6j86tbj1velq11g.apps.googleusercontent.com',
    iosBundleId: 'com.example.interntask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANzNmokpqQzm7HjSRKuW_t8BXaLgBuB3k',
    appId: '1:228043066675:web:b6c5698c4e4cf28d140246',
    messagingSenderId: '228043066675',
    projectId: 'interntask-41be2',
    authDomain: 'interntask-41be2.firebaseapp.com',
    storageBucket: 'interntask-41be2.firebasestorage.app',
    measurementId: 'G-RF515BTFM0',
  );
}
